
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 09 18:40:15 CST 2018
//----------------------------------------------------

package html.org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FINCT = 53;
  public static final int DOSPUNTOS = 12;
  public static final int BOTON = 42;
  public static final int FINCAJATEXTO = 22;
  public static final int FINENLACE = 45;
  public static final int PAREC = 8;
  public static final int PAREA = 7;
  public static final int FINTITULO = 33;
  public static final int FINTEXTOA = 55;
  public static final int CAJA = 38;
  public static final int ENTERO = 3;
  public static final int CUERPO = 30;
  public static final int FINCB = 51;
  public static final int PUNTOCOMA = 18;
  public static final int CJS = 26;
  public static final int CT = 52;
  public static final int FIN = 5;
  public static final int CAJATEXTO = 21;
  public static final int FIL = 48;
  public static final int FINCCSS = 29;
  public static final int MAYORQUE = 11;
  public static final int IGUAL = 6;
  public static final int ENLACE = 44;
  public static final int FINPANEL = 35;
  public static final int FINCJS = 27;
  public static final int TITULO = 32;
  public static final int TEXTOA = 54;
  public static final int FINFIL = 49;
  public static final int FINCHTM = 23;
  public static final int CB = 50;
  public static final int PANEL = 34;
  public static final int FINIMAGEN = 41;
  public static final int ID = 2;
  public static final int CUALQUIERA = 16;
  public static final int FINTABLA = 47;
  public static final int EOF = 0;
  public static final int FINCHTML = 19;
  public static final int DECIMAL = 4;
  public static final int error = 1;
  public static final int ENCABEZADO = 24;
  public static final int CADENA = 13;
  public static final int TABLA = 46;
  public static final int CHTML = 20;
  public static final int MENOS = 14;
  public static final int SALTOFIN = 17;
  public static final int FINCAJA = 39;
  public static final int IMAGEN = 40;
  public static final int CCSS = 28;
  public static final int FINTEXTO = 37;
  public static final int TEXTO = 36;
  public static final int HOLA = 10;
  public static final int EXPRESION = 15;
  public static final int AID = 9;
  public static final int FINCUERPO = 31;
  public static final int FINBOTON = 43;
  public static final int FINENCABEZADO = 25;
}

