/* The following code was generated by JFlex 1.6.1 */

package js.org.compi2.codigo3d.parser;

import java_cup.runtime.Symbol;

//Scanner para generar C3D

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/js/org/compi2/codigo3d/parser/lexico.flex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int EXPRESION = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\14\1\3\1\62\1\14\1\14\22\0\1\14\1\33\1\15"+
    "\2\0\1\23\1\32\1\1\1\21\1\24\1\20\1\16\1\27\1\17"+
    "\1\5\1\2\2\10\1\11\1\7\2\13\4\4\1\12\1\30\1\35"+
    "\1\36\1\34\2\0\1\44\1\6\1\57\1\50\1\42\1\43\2\6"+
    "\1\52\1\61\1\6\1\45\1\53\1\56\1\55\1\60\1\6\1\40"+
    "\1\47\1\37\1\41\1\54\4\6\3\0\1\22\1\6\1\0\1\44"+
    "\1\6\1\57\1\50\1\42\1\43\2\6\1\52\1\61\1\6\1\45"+
    "\1\53\1\56\1\55\1\60\1\6\1\40\1\47\1\37\1\41\1\54"+
    "\4\6\1\25\1\31\1\26\7\0\1\62\252\0\2\51\115\0\1\46"+
    "\u1ea8\0\1\62\1\62\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\2\1\1\24\1\25\1\26"+
    "\1\1\3\6\1\1\2\6\1\1\4\6\1\27\1\30"+
    "\5\0\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\4\6\1\0\1\41\1\6\1\41\1\6\1\0"+
    "\2\6\1\0\2\6\1\0\3\6\1\0\1\3\1\0"+
    "\1\42\4\6\2\0\4\6\1\0\2\6\1\0\2\6"+
    "\1\0\1\6\1\0\2\6\1\3\4\0\1\43\2\6"+
    "\1\0\1\6\1\0\1\44\1\6\1\44\2\6\2\45"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\1\6\2\46"+
    "\1\47\1\0\1\6\1\0\1\6\2\50\1\0\4\6"+
    "\1\0\1\6\1\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\4\6\1\0\1\6\1\0\1\6"+
    "\1\0\1\6\1\0\1\6\2\51\1\0\1\6\1\52"+
    "\1\53\1\6\1\0\1\6\2\54\1\0\1\6\1\0"+
    "\1\55\1\0\2\6\2\56\2\57\2\0\1\6\1\60"+
    "\1\61\2\0\2\62\6\0\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\146\0\146\0\314\0\146"+
    "\0\377\0\146\0\146\0\u0132\0\u0165\0\146\0\146\0\146"+
    "\0\146\0\146\0\146\0\146\0\146\0\146\0\u0198\0\u01cb"+
    "\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363"+
    "\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\146"+
    "\0\146\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7\0\146\0\146"+
    "\0\146\0\146\0\146\0\146\0\146\0\146\0\u05fa\0\u062d"+
    "\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5"+
    "\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d"+
    "\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u05c7\0\u0a5c\0\u0a8f\0\u0ac2"+
    "\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27\0\u0c5a"+
    "\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2"+
    "\0\u0e25\0\u0e58\0\u052e\0\u09f6\0\u0e8b\0\u0ebe\0\u0ef1\0\377"+
    "\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\146\0\u1023\0\377"+
    "\0\u1056\0\u1089\0\146\0\377\0\u10bc\0\u10ef\0\u1122\0\u1155"+
    "\0\u1188\0\u11bb\0\u11ee\0\146\0\377\0\377\0\u1221\0\u1254"+
    "\0\u1287\0\u12ba\0\146\0\377\0\u12ed\0\u1320\0\u1353\0\u1386"+
    "\0\u13b9\0\u13ec\0\u141f\0\u1452\0\u1485\0\u14b8\0\u14eb\0\u151e"+
    "\0\u1551\0\u1584\0\u15b7\0\u15ea\0\u161d\0\u1650\0\u1683\0\u16b6"+
    "\0\u16e9\0\u171c\0\u174f\0\u1782\0\u17b5\0\u17e8\0\u181b\0\u184e"+
    "\0\146\0\377\0\u1881\0\u18b4\0\377\0\377\0\u18e7\0\u191a"+
    "\0\u194d\0\146\0\377\0\u1980\0\u19b3\0\u19e6\0\377\0\u1a19"+
    "\0\u1a4c\0\u1a7f\0\146\0\377\0\146\0\377\0\u1ab2\0\u1ae5"+
    "\0\u1b18\0\377\0\u04fb\0\u1b4b\0\u1b7e\0\146\0\377\0\u1bb1"+
    "\0\u1be4\0\u1c17\0\u1c4a\0\u1c7d\0\u1cb0\0\u04fb";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\3\7"+
    "\1\12\1\7\1\6\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\2\11"+
    "\1\37\2\11\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\3\11\1\46\1\47\1\11\1\0\15\50\1\51\45\50"+
    "\63\0\2\52\1\53\1\6\1\54\2\52\3\55\1\52"+
    "\1\54\47\52\4\0\1\7\1\56\1\11\3\7\1\0"+
    "\1\7\23\0\7\11\1\0\2\11\1\0\10\11\5\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\7\11\1\0"+
    "\2\11\1\0\10\11\17\0\1\57\63\0\1\60\74\0"+
    "\1\61\63\0\1\62\66\0\1\63\62\0\1\64\62\0"+
    "\1\65\62\0\1\66\30\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\1\11\1\67\5\11\1\0\2\11\1\0"+
    "\10\11\5\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\3\11\1\70\3\11\1\0\2\11\1\0\10\11\5\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\2\11\1\71"+
    "\2\11\1\72\1\11\1\0\2\11\1\0\10\11\43\0"+
    "\1\73\6\0\2\74\14\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\3\11\1\75\3\11\1\0\2\11\1\74"+
    "\1\76\7\11\5\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\3\11\1\77\3\11\1\0\2\11\1\100\1\101"+
    "\2\11\1\102\4\11\54\0\1\103\13\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\7\11\1\0\2\11\1\0"+
    "\1\11\1\104\6\11\5\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\3\11\1\105\3\11\1\0\2\11\1\106"+
    "\1\107\7\11\5\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\5\11\1\110\1\11\1\0\2\11\1\0\10\11"+
    "\5\0\1\11\1\0\4\11\1\0\1\11\23\0\5\11"+
    "\1\111\1\11\1\0\2\11\1\0\10\11\1\0\3\52"+
    "\1\6\57\52\2\53\1\112\1\113\57\53\2\52\1\114"+
    "\1\6\61\52\1\114\1\6\1\54\2\52\3\54\1\52"+
    "\1\54\47\52\4\0\1\115\2\0\3\115\1\0\1\115"+
    "\53\0\1\11\1\0\4\11\1\0\1\11\23\0\2\11"+
    "\1\116\4\11\1\0\2\11\1\0\10\11\5\0\1\11"+
    "\1\0\4\11\1\0\1\11\23\0\1\117\6\11\1\0"+
    "\2\11\1\0\10\11\5\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\7\11\1\0\2\11\1\0\4\11\1\120"+
    "\3\11\5\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\6\11\1\121\1\0\2\11\1\0\10\11\46\0\1\122"+
    "\73\0\1\123\10\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\6\11\1\124\1\0\2\11\1\0\10\11\5\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\7\11\1\0"+
    "\2\11\1\0\4\11\1\125\3\11\5\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\1\126\3\11\1\127\2\11"+
    "\1\0\2\11\1\0\10\11\54\0\1\130\13\0\1\11"+
    "\1\0\4\11\1\0\1\11\23\0\7\11\1\0\2\11"+
    "\1\0\1\11\1\131\6\11\5\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\5\11"+
    "\1\132\2\11\61\0\1\133\6\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\6\11"+
    "\1\134\1\11\5\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\7\11\1\0\2\11\1\0\4\11\1\135\3\11"+
    "\43\0\1\136\24\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\3\11\1\137\3\11\1\0\2\11\1\0\10\11"+
    "\5\0\1\11\1\0\4\11\1\0\1\11\23\0\7\11"+
    "\1\140\1\141\1\11\1\0\10\11\5\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\1\11\1\142\5\11\1\0"+
    "\2\11\1\0\10\11\1\0\1\53\1\143\1\112\1\113"+
    "\57\53\2\144\1\145\60\144\3\52\1\6\1\146\2\52"+
    "\1\146\1\147\1\146\1\52\1\146\47\52\4\0\1\11"+
    "\1\0\4\11\1\0\1\11\23\0\3\11\1\150\3\11"+
    "\1\0\2\11\1\0\10\11\5\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\3\11"+
    "\1\151\4\11\5\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\7\11\1\0\2\11\1\0\5\11\1\152\2\11"+
    "\5\0\1\11\1\0\4\11\1\0\1\11\23\0\7\11"+
    "\1\153\1\154\1\11\1\0\10\11\43\0\1\155\75\0"+
    "\1\156\11\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\3\11\1\157\3\11\1\0\2\11\1\0\10\11\5\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\7\11\1\0"+
    "\2\11\1\0\3\11\1\160\4\11\5\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\3\11\1\161\3\11\1\0"+
    "\2\11\1\0\10\11\5\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\3\11\1\162\3\11\1\0\2\11\1\0"+
    "\10\11\55\0\1\163\12\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\7\11\1\0\2\11\1\0\2\11\1\164"+
    "\5\11\5\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\2\11\1\165\4\11\1\0\2\11\1\0\10\11\41\0"+
    "\1\166\26\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\1\11\1\167\5\11\1\0\2\11\1\0\10\11\5\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\7\11\1\170"+
    "\1\171\1\11\1\0\10\11\57\0\1\172\10\0\1\11"+
    "\1\0\4\11\1\0\1\11\23\0\7\11\1\0\2\11"+
    "\1\0\4\11\1\173\3\11\56\0\1\174\11\0\1\11"+
    "\1\0\4\11\1\0\1\11\23\0\7\11\1\0\2\11"+
    "\1\0\3\11\1\175\4\11\5\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\5\11\1\176\1\11\1\0\2\11"+
    "\1\0\10\11\1\0\1\144\1\113\1\145\60\144\2\52"+
    "\1\177\1\6\61\52\1\177\1\6\1\146\2\52\3\146"+
    "\1\52\1\146\47\52\4\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\1\11\1\200\5\11\1\0\2\11\1\0"+
    "\10\11\5\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\7\11\1\0\2\11\1\201\1\202\7\11\43\0\1\203"+
    "\24\0\1\11\1\0\4\11\1\0\1\11\23\0\3\11"+
    "\1\204\3\11\1\0\2\11\1\0\10\11\60\0\1\205"+
    "\7\0\1\11\1\0\4\11\1\0\1\11\23\0\7\11"+
    "\1\0\2\11\1\0\5\11\1\206\2\11\5\0\1\11"+
    "\1\0\4\11\1\0\1\11\23\0\7\11\1\0\2\11"+
    "\1\0\4\11\1\207\3\11\5\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\5\11"+
    "\1\210\2\11\5\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\7\11\1\0\2\11\1\0\1\11\1\211\6\11"+
    "\52\0\2\212\14\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\7\11\1\0\2\11\1\212\1\213\7\11\45\0"+
    "\1\214\22\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\5\11\1\215\1\11\1\0\2\11\1\0\10\11\40\0"+
    "\1\216\27\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\1\217\6\11\1\0\2\11\1\0\10\11\1\0\3\52"+
    "\1\6\4\52\2\220\51\52\4\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\4\11"+
    "\1\221\3\11\56\0\1\222\11\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\3\11"+
    "\1\223\4\11\60\0\1\224\7\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\5\11"+
    "\1\225\2\11\5\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\3\11\1\226\3\11\1\0\2\11\1\0\10\11"+
    "\5\0\1\11\1\0\4\11\1\0\1\11\23\0\1\227"+
    "\6\11\1\0\2\11\1\0\10\11\5\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\3\11\1\230\3\11\1\0"+
    "\2\11\1\0\10\11\54\0\1\231\13\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\7\11\1\0\2\11\1\0"+
    "\1\11\1\232\6\11\62\0\1\233\5\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\7\11\1\0\2\11\1\0"+
    "\7\11\1\234\41\0\1\235\26\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\1\11\1\236\5\11\1\0\2\11"+
    "\1\0\10\11\1\0\3\52\1\6\1\237\2\52\3\237"+
    "\1\52\1\237\47\52\4\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\5\11\1\240\1\11\1\0\2\11\1\0"+
    "\10\11\57\0\1\241\10\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\7\11\1\0\2\11\1\0\4\11\1\242"+
    "\3\11\52\0\2\243\14\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\7\11\1\0\2\11\1\243\1\244\7\11"+
    "\5\0\1\11\1\0\4\11\1\0\1\11\23\0\1\11"+
    "\1\245\5\11\1\0\2\11\1\0\10\11\5\0\1\11"+
    "\1\0\4\11\1\0\1\11\23\0\7\11\1\0\2\11"+
    "\1\0\3\11\1\246\4\11\5\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\0\4\11"+
    "\1\247\3\11\52\0\2\250\14\0\1\11\1\0\4\11"+
    "\1\0\1\11\23\0\7\11\1\0\2\11\1\250\1\251"+
    "\7\11\43\0\1\252\24\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\3\11\1\253\3\11\1\0\2\11\1\0"+
    "\10\11\45\0\1\254\22\0\1\11\1\0\4\11\1\0"+
    "\1\11\23\0\5\11\1\255\1\11\1\0\2\11\1\0"+
    "\10\11\1\0\3\52\1\6\1\256\2\52\3\256\1\52"+
    "\1\256\47\52\4\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\1\11\1\257\5\11\1\0\2\11\1\0\10\11"+
    "\56\0\1\260\11\0\1\11\1\0\4\11\1\0\1\11"+
    "\23\0\7\11\1\0\2\11\1\0\3\11\1\261\4\11"+
    "\5\0\1\11\1\0\4\11\1\0\1\11\23\0\1\262"+
    "\6\11\1\0\2\11\1\0\10\11\41\0\1\263\26\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\1\11\1\264"+
    "\5\11\1\0\2\11\1\0\10\11\47\0\2\265\17\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\7\11\1\265"+
    "\1\266\1\11\1\0\10\11\1\0\3\52\1\6\1\267"+
    "\2\52\3\267\1\52\1\267\47\52\56\0\1\270\10\0"+
    "\1\11\1\0\4\11\1\0\1\11\23\0\7\11\1\0"+
    "\2\11\1\0\4\11\1\271\3\11\5\0\1\11\1\0"+
    "\4\11\1\0\1\11\23\0\7\11\1\0\2\11\1\0"+
    "\3\11\1\272\4\11\1\0\1\52\1\273\1\52\1\6"+
    "\1\274\2\52\1\274\2\275\1\52\1\274\47\52\44\0"+
    "\1\276\22\0\1\11\1\0\4\11\1\0\1\11\23\0"+
    "\5\11\1\277\1\11\1\0\2\11\1\0\10\11\1\0"+
    "\3\52\1\6\6\52\1\300\53\52\1\6\1\274\2\52"+
    "\3\274\1\300\1\274\52\52\1\6\3\52\3\301\1\52"+
    "\1\301\52\52\1\6\1\302\2\52\3\302\1\52\1\302"+
    "\52\52\1\6\6\52\1\303\53\52\1\6\3\52\3\304"+
    "\1\52\1\304\52\52\1\6\1\305\2\52\3\305\1\52"+
    "\1\305\50\52\1\306\1\52\1\6\57\52";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7395];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\1\1\1\11\1\1\2\11"+
    "\2\1\11\11\21\1\2\11\5\0\10\11\4\1\1\0"+
    "\4\1\1\0\2\1\1\0\2\1\1\0\3\1\1\0"+
    "\1\1\1\0\5\1\2\0\4\1\1\0\2\1\1\0"+
    "\2\1\1\0\1\1\1\0\3\1\4\0\3\1\1\0"+
    "\1\1\1\0\1\11\4\1\1\11\2\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\11\2\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\1\0\4\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\4\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\1\0\4\1\1\0\1\1"+
    "\1\11\1\1\1\0\1\1\1\0\1\1\1\0\2\1"+
    "\1\11\1\1\1\11\1\1\2\0\3\1\2\0\1\11"+
    "\1\1\6\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[198];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Código de usuario
    

//VARIALES Y METODOS DEL SCANER
String expresion="";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 220) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error lexico: "+yytext());
            }
          case 52: break;
          case 2: 
            { return new Symbol(sym.DIV         ,yychar,yyline,yytext());
            }
          case 53: break;
          case 3: 
            { 
            }
          case 54: break;
          case 4: 
            { return new Symbol(sym.NUMERO       ,yychar,yyline,new String(yytext()));
            }
          case 55: break;
          case 5: 
            { return new Symbol(sym.PUNTO       ,yychar,yyline,yytext());
            }
          case 56: break;
          case 6: 
            { return new Symbol(sym.ID           ,yychar,yyline, new String(yytext()));
            }
          case 57: break;
          case 7: 
            { return new Symbol(sym.DOSPUNTOS        ,yychar,yyline,yytext());
            }
          case 58: break;
          case 8: 
            { yybegin (EXPRESION);
            }
          case 59: break;
          case 9: 
            { return new Symbol(sym.MAS         ,yychar,yyline,yytext());
            }
          case 60: break;
          case 10: 
            { return new Symbol(sym.MENOS       ,yychar,yyline,yytext());
            }
          case 61: break;
          case 11: 
            { return new Symbol(sym.POR         ,yychar,yyline,yytext());
            }
          case 62: break;
          case 12: 
            { return new Symbol(sym.PAREA       ,yychar,yyline,yytext());
            }
          case 63: break;
          case 13: 
            { return new Symbol(sym.ELEVA       ,yychar,yyline,yytext());
            }
          case 64: break;
          case 14: 
            { return new Symbol(sym.MOD       ,yychar,yyline,yytext());
            }
          case 65: break;
          case 15: 
            { return new Symbol(sym.PAREC        ,yychar,yyline,yytext());
            }
          case 66: break;
          case 16: 
            { return new Symbol(sym.LLV1        ,yychar,yyline,yytext());
            }
          case 67: break;
          case 17: 
            { return new Symbol(sym.LLV2        ,yychar,yyline,yytext());
            }
          case 68: break;
          case 18: 
            { return new Symbol(sym.COMA        ,yychar,yyline,yytext());
            }
          case 69: break;
          case 19: 
            { return new Symbol(sym.PUNTOCOMA   ,yychar,yyline,yytext());
            }
          case 70: break;
          case 20: 
            { return new Symbol(sym.NEL         ,yychar ,yyline, yytext());
            }
          case 71: break;
          case 21: 
            { return new Symbol(sym.MAYORQUE    ,yychar,yyline,yytext());
            }
          case 72: break;
          case 22: 
            { return new Symbol(sym.MENORQUE    ,yychar,yyline,yytext());
            }
          case 73: break;
          case 23: 
            { expresion +=yytext();
            }
          case 74: break;
          case 24: 
            { String temporal=expresion; 
        expresion=""; 
        yybegin(YYINITIAL); 
        return new Symbol(sym.CADENA, yyline+1, yyline, temporal);
            }
          case 75: break;
          case 25: 
            { return new Symbol(sym.MASMAS      ,yychar,yyline,yytext());
            }
          case 76: break;
          case 26: 
            { return new Symbol(sym.MENOSMENOS  ,yychar,yyline,yytext());
            }
          case 77: break;
          case 27: 
            { return new Symbol(sym.OR          ,yychar ,yyline,yytext());
            }
          case 78: break;
          case 28: 
            { return new Symbol(sym.Y           ,yychar ,yyline,yytext());
            }
          case 79: break;
          case 29: 
            { return new Symbol(sym.NOIGUAL     ,yychar,yyline, yytext());
            }
          case 80: break;
          case 30: 
            { return new Symbol(sym.MAYORIGUAL  ,yychar,yyline,yytext());
            }
          case 81: break;
          case 31: 
            { return new Symbol(sym.MENORIGUAL  ,yychar,yyline, yytext());
            }
          case 82: break;
          case 32: 
            { return new Symbol(sym.IGUALIGUAL  ,yychar,yyline, yytext());
            }
          case 83: break;
          case 33: 
            { return new Symbol(sym.SI          ,yychar,yyline, yytext());
            }
          case 84: break;
          case 34: 
            { return new Symbol(sym.NDECIMAL     ,yychar, yyline, new String(yytext()));
            }
          case 85: break;
          case 35: 
            { return new Symbol(sym.VERDADERO   ,yychar,yyline, yytext());
            }
          case 86: break;
          case 36: 
            { return new Symbol(sym.SINO        ,yychar,yyline, yytext());
            }
          case 87: break;
          case 37: 
            { return new Symbol(sym.DIMV        ,yychar,yyline, yytext());
            }
          case 88: break;
          case 38: 
            { return new Symbol(sym.CASO        ,yychar,yyline, yytext());
            }
          case 89: break;
          case 39: 
            { return new Symbol(sym.PARA        ,yychar,yyline, yytext());
            }
          case 90: break;
          case 40: 
            { return new Symbol(sym.FALSO       ,yychar,yyline, yytext());
            }
          case 91: break;
          case 41: 
            { return new Symbol(sym.FUNCION     ,yychar,yyline, yytext());
            }
          case 92: break;
          case 42: 
            { return new Symbol(sym.TERMINAR    ,yychar,yyline, yytext());
            }
          case 93: break;
          case 43: 
            { return new Symbol(sym.DEFECTO     ,yychar,yyline, yytext());
            }
          case 94: break;
          case 44: 
            { return new Symbol(sym.MENSAJEV    ,yychar,yyline, yytext());
            }
          case 95: break;
          case 45: 
            { return new Symbol(sym.RETORNAR    ,yychar,yyline, yytext());
            }
          case 96: break;
          case 46: 
            { return new Symbol(sym.IMPRIMIR    ,yychar,yyline, yytext());
            }
          case 97: break;
          case 47: 
            { return new Symbol(sym.MIENTRAS    ,yychar,yyline, yytext());
            }
          case 98: break;
          case 48: 
            { return new Symbol(sym.DOCUMENTO   ,yychar,yyline, yytext());
            }
          case 99: break;
          case 49: 
            { return new Symbol(sym.DATE         ,yychar,yyline,new String(yytext()));
            }
          case 100: break;
          case 50: 
            { return new Symbol(sym.SELECCIONA ,yychar,yyline, yytext());
            }
          case 101: break;
          case 51: 
            { return new Symbol(sym.DATETIME     ,yychar,yyline,new String(yytext()));
            }
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
