
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 02 19:35:37 CST 2018
//----------------------------------------------------

package js.org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 49;
  public static final int NUMERO = 43;
  public static final int MASMAS = 2;
  public static final int CASO = 33;
  public static final int Y = 17;
  public static final int PAREC = 10;
  public static final int MENOSMENOS = 3;
  public static final int PAREA = 8;
  public static final int POR = 6;
  public static final int IMPRIMIR = 38;
  public static final int DATETIME = 42;
  public static final int SI = 30;
  public static final int DOCUMENTO = 50;
  public static final int FUNCION = 39;
  public static final int PUNTOCOMA = 15;
  public static final int DATE = 41;
  public static final int NOIGUAL = 25;
  public static final int MENORIGUAL = 23;
  public static final int MAYORQUE = 20;
  public static final int CARACTER = 45;
  public static final int SINO = 31;
  public static final int OR = 16;
  public static final int MIENTRAS = 36;
  public static final int DIV = 7;
  public static final int DIMV = 28;
  public static final int MENSAJEV = 40;
  public static final int ID = 46;
  public static final int MAYORIGUAL = 22;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int CADENA = 47;
  public static final int MENOS = 5;
  public static final int ELEVA = 9;
  public static final int MOD = 48;
  public static final int NDECIMAL = 44;
  public static final int NEL = 18;
  public static final int MENORQUE = 21;
  public static final int SELECCIONA = 32;
  public static final int PUNTO = 19;
  public static final int IGUALIGUAL = 24;
  public static final int LLV2 = 12;
  public static final int FALSO = 27;
  public static final int LLV1 = 11;
  public static final int TERMINAR = 37;
  public static final int DOSP = 14;
  public static final int PARA = 35;
  public static final int RETORNAR = 29;
  public static final int VERDADERO = 26;
  public static final int DEFECTO = 34;
  public static final int MAS = 4;
}

