
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 19 20:34:18 CST 2018
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 56;
  public static final int FUNCTION = 36;
  public static final int READLINE = 64;
  public static final int PAREC = 7;
  public static final int PAREA = 6;
  public static final int POR = 4;
  public static final int CHAR = 28;
  public static final int CASE = 51;
  public static final int DOUBLE = 29;
  public static final int INTEGER = 26;
  public static final int PRIVATE = 22;
  public static final int FOR = 43;
  public static final int NOIGUAL = 15;
  public static final int STATIC = 24;
  public static final int NOT = 54;
  public static final int AND = 52;
  public static final int MENORIGUAL = 13;
  public static final int ELSEIF = 41;
  public static final int MAYORQUE = 10;
  public static final int IGUAL = 14;
  public static final int CARACTER = 57;
  public static final int OR = 53;
  public static final int DIV = 5;
  public static final int UNTIL = 49;
  public static final int SELECT = 50;
  public static final int EXIT = 55;
  public static final int LOOP = 48;
  public static final int NEXT = 46;
  public static final int IF = 38;
  public static final int MAIN = 35;
  public static final int AMPERSAND = 16;
  public static final int ID = 58;
  public static final int MAYORIGUAL = 12;
  public static final int DIM = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 27;
  public static final int RETURN = 37;
  public static final int BYVAL = 33;
  public static final int TRUE = 17;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int CADENA = 59;
  public static final int MENOS = 3;
  public static final int NDECIMAL = 60;
  public static final int MENORQUE = 11;
  public static final int MODULE = 19;
  public static final int WRITELINE = 63;
  public static final int ELSE = 39;
  public static final int PUNTO = 9;
  public static final int TO = 44;
  public static final int WHILE = 42;
  public static final int PUBLIC = 21;
  public static final int THEN = 40;
  public static final int END = 20;
  public static final int LONG = 30;
  public static final int STRING = 31;
  public static final int CORC = 62;
  public static final int CORA = 61;
  public static final int FALSE = 18;
  public static final int AS = 25;
  public static final int SUB = 34;
  public static final int DO = 47;
  public static final int CONSOLE = 32;
  public static final int STEP = 45;
  public static final int MAS = 2;
}

