
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 12 22:38:08 CST 2018
//----------------------------------------------------

package org.compi2.codigo3d.parser.css;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENTER = 43;
  public static final int MINUSCULA = 40;
  public static final int CAPITAL = 41;
  public static final int PAREC = 6;
  public static final int PAREA = 5;
  public static final int POR = 10;
  public static final int NEGRILLA = 37;
  public static final int ENTERO = 15;
  public static final int COLORTEXT = 22;
  public static final int JUSTIFICADO = 36;
  public static final int IZQUIERDA = 33;
  public static final int PUNTOCOMA = 7;
  public static final int MAYORQUE = 2;
  public static final int IGUAL = 3;
  public static final int DOSPI = 17;
  public static final int FORMATO = 30;
  public static final int LETRA = 29;
  public static final int ALINEADO = 32;
  public static final int DIV = 11;
  public static final int MAYUSCULA = 39;
  public static final int GRUPO = 42;
  public static final int CURSIVA = 38;
  public static final int ID = 14;
  public static final int AUTOREDIMENSION = 26;
  public static final int EOF = 0;
  public static final int DECIMAL = 16;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int CADENA = 21;
  public static final int TAMTEXT = 28;
  public static final int MENOS = 8;
  public static final int CORCHC = 13;
  public static final int FONDOELEMENTO = 27;
  public static final int CORCHA = 12;
  public static final int MENORQUE = 4;
  public static final int OPAQUE = 23;
  public static final int DERECHA = 34;
  public static final int CENTRADO = 35;
  public static final int TEXT = 31;
  public static final int FALSE = 20;
  public static final int BORDE = 24;
  public static final int VISIBLE = 25;
  public static final int MAS = 9;
}

